# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['launch.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend/app', 'backend/app'),
        ('backend/requirements.txt', 'backend'),
        ('desktop_app.py', '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'nicegui',
        'nicegui.ui',
        'nicegui.functions',
        'nicegui.native',
        'nicegui.element',
        'nicegui.elements',
        'nicegui.page',
        'nicegui.context',
        'nicegui.events',
        'nicegui.dataclasses',
        'nicegui.app',
        'nicegui.settings',
        'starlette',
        'starlette.applications',
        'starlette.middleware',
        'starlette.requests',
        'starlette.responses',
        'starlette.routing',
        'starlette.staticfiles',
        'starlette.templating',
        'starlette.websockets',
        'starlette.datastructures',
        'fastapi',
        'fastapi.middleware',
        'fastapi.staticfiles',
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.pool',
        'aiosqlite',
        'mqtt',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'aiofiles',
        'pkg_resources',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='uartscope',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
